insert into products (product_name, category, price) values ('Adjustable Pedicure Footrest', 'Beauty', 39.99);
insert into products (product_name, category, price) values ('Home Office Chair', 'Furniture', 199.99);
insert into products (product_name, category, price) values ('Silicone Baking Mat Set', 'Kitchen', null);
insert into products (product_name, category, price) values ('Safety Goggles', 'Safety', 14.99);
insert into products (product_name, category, price) values ('Bamboo Toothbrush Holder', 'Health', 14.99);
insert into products (product_name, category, price) values ('Lentil Vegetable Stew', 'Food - Canned Soups', 4.49);
insert into products (product_name, category, price) values ('Almond Joy Bars', 'Food - Confectionery', 1.29);
insert into products (product_name, category, price) values ('Protein Bar Variety Pack', 'Food - Snacks', 12.99);
insert into products (product_name, category, price) values ('Graphic Tee', 'Clothing', 19.99);
insert into products (product_name, category, price) values ('Basil-infused Olive Oil', null, 6.99);
insert into products (product_name, category, price) values ('Smartwatch', 'Wearable Tech', 199.99);
insert into products (product_name, category, price) values ('Cucumber Lime Sparkling Water', 'Food - Beverages', 1.49);
insert into products (product_name, category, price) values ('Tactical Backpack', null, null);
insert into products (product_name, category, price) values ('Pet Water Fountain with Filtration', 'Pets', 39.99);
insert into products (product_name, category, price) values ('Sliced Bell Peppers', null, 3.99);
insert into products (product_name, category, price) values ('Frozen Fruit Medley', 'Food - Frozen Foods', 5.99);
insert into products (product_name, category, price) values ('Indoor Plants', 'Garden', 19.99);
insert into products (product_name, category, price) values ('Freestanding Wine Rack', 'Home', 79.99);
insert into products (product_name, category, price) values ('Window A/C Unit', 'Home Appliances', 299.99);
insert into products (product_name, category, price) values ('Waffle Maker', null, 39.99);
insert into products (product_name, category, price) values ('Watering Can with Nozzle', 'Garden', 19.99);
insert into products (product_name, category, price) values ('Electric Meat Grinder', 'Kitchen', 89.99);
insert into products (product_name, category, price) values ('Emergency Preparedness Kit', 'Safety', null);
insert into products (product_name, category, price) values ('Smart WiFi Plug', 'Smart Home', 19.99);
insert into products (product_name, category, price) values ('Lemon Zest Olive Oil', 'Food - Oils & Vinegars', 8.99);
insert into products (product_name, category, price) values ('Honey Almond Granola Bars', 'Food - Snacks', 3.99);
insert into products (product_name, category, price) values ('Orange Ginger Vinaigrette', 'Food - Condiments', 3.99);
insert into products (product_name, category, price) values ('Set of Herb Garden Markers', 'Garden', 8.99);
insert into products (product_name, category, price) values ('Samsung Galaxy Smartwatch', 'Wearable Tech', 249.99);
insert into products (product_name, category, price) values ('Digital Bullet Journal', 'Apps', 24.99);
insert into products (product_name, category, price) values ('Coffee Capsule Dispenser', 'Kitchen', 24.99);
insert into products (product_name, category, price) values ('Pet First Aid Kit', 'Pets', 29.99);
insert into products (product_name, category, price) values ('Chocolate Coconut Protein Balls', 'Food - Snacks', 2.99);
insert into products (product_name, category, price) values ('Bike Helmet', 'Bicycles', 34.99);
insert into products (product_name, category, price) values ('Basmati Rice', 'Food - Grains', 5.79);
insert into products (product_name, category, price) values ('Fleece Lined Leggings', 'Clothing', 29.99);
insert into products (product_name, category, price) values ('Pet Caress Brush', 'Pets', 12.99);
insert into products (product_name, category, price) values ('High-Speed Hand Blender', 'Kitchen', 39.99);
insert into products (product_name, category, price) values ('Tomato Basil Soup', 'Food - Canned Goods', 3.49);
insert into products (product_name, category, price) values ('Coconut Flakes', 'Food - Baking', 3.29);
